### ISSUE TITLE
About training iterations

### ISSUE THREAD

**Issue by lovejing0306** [RedAIGC/Target-Driven-Distillation#4]
The training iterations in your paper are 20000, but in your codes, the training iterations are 100000. Can you tell me why?
![Xnip2024-09-29_16-48-56](https://github.com/user-attachments/assets/45e7b395-0489-4fc8-b8b4-451bc6d2829a)

**Comment by palmerkuo** [comment]
We tested some models from the later training stages, and they performed worse on certain quantitative metrics compared to the current model. The final released model corresponds to the one at 20k steps. @lovejing0306

**Comment by lovejing0306** [comment]
> We tested some models from the later training stages, and they performed worse on certain quantitative metrics compared to the current model. The final released model corresponds to the one at 20k steps. @lovejing0306

ok, thanks. I have another question. Why do you set the cfg=3.5 in your paper?

**Comment by WangCunzheng** [comment]
> > 我们测试了一些来自后期训练阶段的模型，与当前模型相比，它们在某些定量指标上的表现更差。最终发布的模型对应于 20k 步长的模型。
> 
> 好的，谢谢。我还有另一个问题。为什么在你的论文中设置 cfg=3.5？

Hello, regarding setting cfg to 3.5, we found during our training process that larger values (such as 7.5) also lead to low content richness and excessive contrast in the images. Extremely small values (exaggeratedly set to 1) make it difficult to select cfg during training and inference, resulting in poor overall image structure. The value of 3.5 is a balanced setting we tested. You can also adjust it according to different base models and the effects you want to achieve.

**Comment by lovejing0306** [comment]
> > > 我们测试了一些来自后期训练阶段的模型，与当前模型相比，它们在某些定量指标上的表现更差。最终发布的模型对应于 20k 步长的模型。
> > 
> > 
> > 好的，谢谢。我还有另一个问题。为什么在你的论文中设置 cfg=3.5？
> 
> Hello, regarding setting cfg to 3.5, we found during our training process that larger values (such as 7.5) also lead to low content richness and excessive contrast in the images. Extremely small values (exaggeratedly set to 1) make it difficult to select cfg during training and inference, resulting in poor overall image structure. The value of 3.5 is a balanced setting we tested. You can also adjust it according to different base models and the effects you want to achieve.

ok, thanks for your reply
