### ISSUE TITLE
whether is γ-sampler not quite consistent with the formulas in the paper?  

### ISSUE THREAD

**Issue by bigmover** [RedAIGC/Target-Driven-Distillation#7]
![image](https://github.com/user-attachments/assets/4c3a12da-1578-4431-a1bd-6ea5dd51bd49)
and
the code as[L259 ](https://github.com/RedAIGC/Target-Driven-Distillation/blob/a463d792a424f14a7fa00ccb4615a13294d6cf8c/tdd_scheduler.py#L259).

**Comment by WangCunzheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/26063296/377699929-4c3a12da-1578-4431-a1bd-6ea5dd51bd49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTE0NjcsIm5iZiI6MTczMDgxMTE2NywicGF0aCI6Ii8yNjA2MzI5Ni8zNzc2OTk5MjktNGMzYTEyZGEtMTU3OC00NDMxLWExYmQtNmVhNWRkNTFiZDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDEyNTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZTg2OTFlOTBhZDdlZWI1Y2QwMDE4MGNjMWUyODRjY2M2NzFlOTczMjc5NGJiOGZhNGRlMDkyZTYzYzgyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mhSHTRj5aWrY5PQNcePXpuitTUQlLw-cseUu_LGczas)代码为[L259 ](https://github.com/RedAIGC/Target-Driven-Distillation/blob/a463d792a424f14a7fa00ccb4615a13294d6cf8c/tdd_scheduler.py#L259)。

Hello, this is consistent. The only difference is that in the code, alpha_prod_t_prev is the square of alpha_p. This discrepancy arises to maintain consistency with the majority of sampler definitions within the diffusers library.

**Comment by bigmover** [comment]
I see now!
